name = "GitHub Action using W3C validator for HTML and CSS"
copyright = "Â© 2023 Wild Tech 'Garden'"
description = "GitHub action using W3C's validator to validate the HTML and CSS of a website"

[module]
[module.hugoVersion]
min = "0.112.7"
extended = false
